### ISSUE TITLE
Persist app page state when wallet window is closed

### ISSUE THREAD

**Issue by danwag06** [bitcoin-sv/spv-wallet-browser#11]
When the wallet window closes, the wallet will always re-launch to the main BsvWallet.tsx page. Use the [ChromeStorageService](https://github.com/bitcoin-sv/spv-wallet-browser/blob/main/src/services/ChromeStorage.service.ts) and a new item in the [ChromeStorageObject](https://github.com/bitcoin-sv/spv-wallet-browser/blob/c81d530f81acc2be6cc3cfd29fd3ee3782902b28/src/services/types/chromeStorage.types.ts#L59) to track page state so that when a user relaunches the wallet, they can pick up where they left off.

**Comment by od-hunter** [comment]
Hi @danwag06 , can I be assigned this when the od hack starts please? I can handle this and I’m ready to work

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
**Persist app page state when wallet window is closed**

Hello SPV Wallet Browser team,

I am Joel Vargas, and I'm a member of Dojo Coding. I also come from OnlyDust.

I would like to request the assignment of this issue. Below is my proposed approach for implementing this issue:

### How I plan on tackling this issue
**Summary:** When a user closes and reopens the wallet, it currently defaults to the main BsvWallet.tsx page. To improve the user experience, I propose using ChromeStorageService to store the current state of the wallet interface. By tracking page state in the ChromeStorageObject, the wallet will be able to restore the user’s last viewed page upon reopening, ensuring a seamless continuation from where they left off.

## Approach:

- State Persistence in ChromeStorage:

Implement a new key in the ChromeStorageObject to track the wallet's page state, ensuring it's stored before the wallet window is closed.
Modify the getAndSetStorage method in ChromeStorageService to retrieve the stored page state and update the wallet’s initial rendering based on that state.
Page State Management:

In the wallet components (BsvWallet.tsx and other related components), we can update the lifecycle methods (such as componentWillUnmount in class components or useEffect cleanup in functional components) to save the current state into Chrome’s local storage before the wallet closes.
On re-launch, we will retrieve this state and navigate the user to the correct page instead of the default BsvWallet.tsx page.
Integration with ChromeStorageService:

Extend the existing ChromeStorageService class to include methods like savePageState and retrievePageState.
These methods will interact with the new page state property within ChromeStorageObject and ensure the correct state is saved and retrieved.
Example Code Snippets:

Storing the page state:

```
class BsvWallet extends React.Component {
  componentWillUnmount() {
    const currentPage = this.props.currentPage;
    ChromeStorageService.updateNested('pageState', { currentPage });
  }
}
```

Retrieving the page state:

```
async function initializeWallet() {
  const storage = await ChromeStorageService.getAndSetStorage();
  const lastPageState = storage.pageState?.currentPage || 'BsvWallet';
  navigateTo(lastPageState); 
}
```

Best regards,
Joel

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To persist the app's page state when the wallet window is closed, I will use the `ChromeStorageService` to store the current page state in a new item within the `ChromeStorageObject`. This will allow the app to track where the user last was. When the wallet is relaunched, instead of defaulting to the main `BsvWallet.tsx page,` the stored page state will be retrieved, enabling users to pick up where they left off. This approach will ensure a seamless user experience by keeping the page state intact across wallet reopens. The implementation will include saving and loading the state efficiently.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have some blockchain experience and want to actively contribute to the projects to enhance my experience.

### How I plan on tackling this issue
I would approach this problem by implementing a new state property, lastVisitedPage, on ChromeStorageObject in ChromeStorageService. For every navigation to a different page, update this property. On wallet restart, take the lastVisitedPage from ChromeStorageService and re-direct the user to the page stored instead of the page from BsvWallet.tsx.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
To handle the wallet window re-launching behavior, I will use the ChromeStorageService to track the user's page state and ensure they can resume from where they left off when the wallet is relaunched. Here’s the plan:

Track Page State: I will create a new item in the ChromeStorageObject that stores the current page or view within the wallet. Whenever the user navigates to a new page (e.g., a specific transaction or settings), this state will be saved in the ChromeStorageService.
Persist State on Wallet Close: When the wallet window closes, the last known page state will remain stored in ChromeStorage. This ensures that even if the user closes and later reopens the wallet, their previous state is preserved.
Re-launch Wallet to Saved State: Upon relaunch, I’ll modify the logic in BsvWallet.tsx to first check for the saved state in ChromeStorageService. If a state is found, the wallet will resume from the stored page instead of re-launching to the main BsvWallet.tsx page by default.
Testing & Refinement: I will thoroughly test the wallet to ensure that the state tracking and re-launch functionality work as expected, allowing users to pick up exactly where they left off.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make sure it is working and responsive accross all devices

**Comment by mimisavage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hi, I’m Mimi Sav, a frontend and blockchain developer. This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.

### How I plan on tackling this issue
To tackle this issue, I would first modify the ⁠ ChromeStorageObject ⁠ to include a new item specifically designed to store the page state. This will allow me to track the user's last interaction with the wallet. Then, I would utilize the ⁠ ChromeStorageService ⁠ to save the state before the wallet window closes. When the user reopens the wallet, I’ll use this stored state to reload the wallet at the same page they were on, rather than defaulting to the main ⁠ BsvWallet.tsx ⁠ page. This ensures a seamless user experience

**Comment by Ekene001** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

### How I plan on tackling this issue
To tackle the task of maintaining the wallet's state when the wallet window closes and relaunches, the approach will involve integrating a persistent state management solution using Chrome's storage capabilities. The solution will be implemented in three steps:

First, I will utilize the ChromeStorageService to store the current page state in the Chrome storage. This will involve creating a new item in the ChromeStorageObject to track the user's current page or activity within the wallet. Whenever the user navigates to a different page, the wallet will update the stored state accordingly, ensuring the most recent state is saved before the window closes.

Second, I will modify the wallet's relaunch functionality to check for the saved state in the ChromeStorageObject. When the wallet window reopens, it will first query the storage service to retrieve the last known state. If a saved state exists, the wallet will direct the user back to that specific page instead of defaulting to the main BsvWallet.tsx page. If no saved state is found, the wallet will continue to load the main page as usual.

Finally, I will implement error handling and state validation to ensure the wallet does not encounter issues when retrieving or applying the stored state. This will include fallback mechanisms that redirect the user to the main page if the stored state is invalid or corrupted.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have experience implementing user-friendly features in web applications, particularly in managing state and user navigation within wallet interfaces.



### How I plan on tackling this issue
I would utilize the ChromeStorageService to track the current page state in the ChromeStorageObject. When the wallet window closes, this state will be saved, allowing the user to return to their last visited page upon relaunch, rather than defaulting to the main BsvWallet.tsx page. This enhances the overall user experience.

**Comment by danwag06** [comment]
@Ekene001 please confirm assignment

**Comment by Ekene001** [comment]
> When the wallet window closes, the wallet will always re-launch to the main BsvWallet.tsx page. Use the [ChromeStorageService](https://github.com/bitcoin-sv/spv-wallet-browser/blob/main/src/services/ChromeStorage.service.ts) and a new item in the [ChromeStorageObject](https://github.com/bitcoin-sv/spv-wallet-browser/blob/c81d530f81acc2be6cc3cfd29fd3ee3782902b28/src/services/types/chromeStorage.types.ts#L59) to track page state so that when a user relaunches the wallet, they can pick up where they left off.

@danwag06 Thank you sir, I will make a PR soon

**Comment by Ekene001** [comment]
@danwag06 Good day Sir,
Please what's your telegram username

**Comment by danwag06** [comment]
@Ekene001 @danwag06 on telegram too
