### ISSUE TITLE
Select and list multiple 1sat ordinal NFTs for sale on the global orderbook.

### ISSUE THREAD

**Issue by danwag06** [bitcoin-sv/spv-wallet-browser#4]
Similar to #3 , the wallet currently supports listing ordinal NFTs for sale on the global orderbook. It would be nice to support selecting and listing multiple at the same time. It can become cumbersome for users who wish to list many items for sale by doing it one by one.

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
software engineering background & smart contract dev, also a contributor to similar projects(https://app.onlydust.com/u/Josh-121) looking to make first contribution here.

### How I plan on tackling this issue
Modify the UI where necessary to allow users to select multiple NFTs at once. This can be done by adding checkboxes next to each NFT or enablingg a multi-selection mode.
Backend Logic for Batch Listing:

Update the listing function to handle multiple NFTs. This could involve creating a abatch request that lists all selected NFTs at once, rather than one by one.

Ensure that the wallet can aggregate multiple listing requests into a single transaction where possible, or handle them sequentially if necessary.

work on feedback & recommendations and deliver swiftly

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I'm a blockchain developer and keen towards contributing to open source and to fix the issues.

### How I plan on tackling this issue
I would implement bulk listing wherein users can select multiple Ordinal NFTs so they can be listed all at once on the global orderbook. This would give a user-experience-enhancing feature: saving the users time and effort in managing multiple listings.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have a solid background in front-end development and experience working with blockchain technologies, particularly in creating user-friendly dApps for managing NFTs. My previous projects include implementing features that enhance user interactions, such as batch actions for listing and selling NFTs. This experience enables me to design and implement a seamless multi-listing feature that simplifies the process for users.



### How I plan on tackling this issue
I would enhance the user interface to allow multi-selection of ordinal NFTs using checkboxes, enabling users to select multiple items for listing at once. I would then modify the listing logic to support batch processing, ensuring the backend can handle multiple NFTs in a single transaction. Input validation would be implemented to ensure correct pricing and required information for all selected items. Additionally, I would provide clear user feedback during the listing process and conduct thorough testing to ensure the feature works seamlessly across various scenarios. This approach will streamline the listing process and improve the user experience.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
i have prior experience on this and willing to contribute

**Comment by danwag06** [comment]
@aniruddhaaps please confirm assignment

**Comment by aniruddhaaps** [comment]
working on it right sir @danwag06

**Comment by JoE11-y** [comment]
Can I complete this @danwag06 ?
