### ISSUE TITLE
Save Wallet Name and Url Image on creation

### ISSUE THREAD

**Issue by danwag06** [bitcoin-sv/spv-wallet-browser#5]
The wallet currently supports giving different accounts a name (label) and a url icon. The request would be to optionally save this information when creating/restoring/importing the wallet.

When saving you'll want to do something similar to this to save the name and/or icon in chrome local storage:

https://github.com/bitcoin-sv/spv-wallet-browser/blob/c81d530f81acc2be6cc3cfd29fd3ee3782902b28/src/pages/Settings.tsx#L223

There are a number of different ways a user can create/import/restore a wallet which can be found here:
https://github.com/bitcoin-sv/spv-wallet-browser/tree/main/src/pages/onboarding

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
am a frontend developer i have experience using frontend technologies

### How I plan on tackling this issue
Kindly assign me ETA <= 48hrs

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
software engineering background with great experience contributing on similar projects(https://app.onlydust.com/u/Josh-121) looking to make first contribution here

### How I plan on tackling this issue
I would use Chrome's local storage to store the label and icon. The provided example link from the spv-wallet-browser codebase demonstrates how to save settings into Chrome’s local storage. 

Test wallet creation, restoration, and import flows to ensure that the label and icon are saved correctly and displayed upon reloading the wallet.

work on feedback & recommendations on time and ensure contact

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.


### How I plan on tackling this issue
To implement this feature, I would first analyze how the wallet currently supports adding names (labels) and URL icons, specifically looking at the existing logic in `Settings.tsx`, which demonstrates how to store this information in Chrome’s local storage. I would then extend this functionality to the wallet creation, restore, and import flows by reviewing the relevant onboarding processes located in `src/pages/onboarding`.

My approach would involve identifying the key points in the onboarding process where wallets are created or imported, and ensuring that, if a label or icon is provided, it gets saved seamlessly in local storage. By reusing the existing logic from the settings page and adapting it for wallet onboarding, I’ll ensure that users can consistently save and retrieve wallet labels and icons, improving the overall user experience without disrupting the existing flow.  @danwag06 it would be awesome if you let me contribute to this amazing project!

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make it is working and responsive accross all devices

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have some experience in blockchain development and want to contribute to the open source projects and want to fix the issues raised.

### How I plan on tackling this issue
I shall modify the onboarding flow to save account names and icons optionally, making it easier to create and import accounts from a wallet. There is similar logic implemented in Settings.tsx at Line 223-it saves the label of the account and icon in chrome's local storage at the time of wallet creation, import, and restore. Therefore, it will ensure a smooth experience across all methods of wallet setup.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Issue #5: Save Wallet Name and URL Image on Creation

Extend Wallet Creation Logic: I’ll modify the wallet creation, import, and restore flows to include optional inputs for the wallet name (label) and a URL for the wallet icon. These options will be displayed during the onboarding process, allowing users to set the name and icon as part of the wallet creation steps.

Add Name and Icon Fields to the Onboarding Pages: I’ll update the relevant onboarding pages in spv-wallet-browser/src/pages/onboarding to capture the wallet name and icon URL during wallet creation. This includes:
Adding input fields for the user to optionally enter a wallet name and icon.
Ensuring these fields are available when the wallet is created, restored, or imported.

Modify Wallet Storage Logic: I’ll adjust the wallet storage logic to save the provided wallet name and icon. Using the same structure from the handleAccountEditSave function, I’ll integrate this logic into the wallet creation process. When a new wallet is created, restored, or imported, the name and icon will be stored in Chrome local storage. If there is not provided name and icon, a default value for these would be saved pending when they edit it.

Update handleAccountEditSave to Ensure Consistency: I’ll ensure that the handleAccountEditSave function in Settings.tsx remains consistent with the new creation logic. If a user edits an existing wallet’s name or icon, the same process for updating the Chrome storage will apply, keeping all wallet-related information synchronized.
Ensure Compatibility with All Onboarding Flows: I’ll verify that the new logic integrates smoothly with all the ways a user can create/import/restore a wallet. This means I’ll ensure consistency in the onboarding process across all wallet creation methods outlined in the repo:
Wallet creation
Wallet import
Wallet restoration

Testing and Validation: I’ll write tests to verify the following:
The wallet name and icon can be optionally set during creation, import, or restoration.
The name and icon are correctly saved in Chrome local storage.
The wallet name and icon persist across different wallet interactions and display correctly in the UI.

UI/UX Refinements: I’ll ensure the input fields for wallet name and icon are easy to use and visually consistent with the rest of the onboarding UI. I’ll also ensure that, when no name or icon is provided, default values are used (e.g., a default wallet name or icon).

Expected time of delivery would be 2-4 days from being assigned.

**Comment by mimisavage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hi, I’m Mimi Sav, a frontend and blockchain developer. This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.



### How I plan on tackling this issue
I will review the existing onboarding processes to identify integration points for these features. Using Chrome's local storage, I will implement optional fields for users to input names and icons, saving this information similarly to the linked code. I'll ensure default values are maintained when users don’t provide inputs and conduct testing to confirm everything works smoothly. This enhancement will improve the user experience by making account management easier.

**Comment by danwag06** [comment]
Hello all - This issue is currently under development in the parent Yours repo as seen here:
https://github.com/yours-org/yours-wallet/issues/245

I'm going to give @maxslimb an opportunity to sign up for OD and earn from the hackathon since they're already working on it. If I haven't heard back in a day or so we will select an new applicant!

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
The goal is to optionally save the wallet name (label) and URL icon when creating, restoring, or importing a wallet. This information will be stored in Chrome's local storage, similar to how account editing is currently handled.

Here is how i plan to tackle this task:
1. I will  need to modify the existing functions that handle wallet creation, restoration, and import to accept and process the new optional parameters.
Similar modifications should be made to the `RestoreAccount.tsx` and `ImportAccount.tsx` components.
2. I will update the `ChromeStorageService` to handle the new fields when adding or updating accounts.
3. I will update the UI to reflect the new information.

## I would make sure to:
1. Handle cases where the name or icon URL is not provided, using default values as necessary.
2. Validate the icon URL to ensure it's a valid image URL before saving.
3. Consider adding a feature to update the account name and icon in the account settings page.
4. Ensure that the new fields are properly synced across devices if your wallet supports multi-device synchronization.

I would try to reavh out if i encounter any challenges. My ETA is 48hrs. Thanks.

**Comment by jimenezz22** [comment]
I am Luis Jiménez, an active member of the Dojo Coding community in Costa Rica, with experience in Cairo and TypeScript

Here’s my approach for solving this issue:

1. **Extend `handleAccountEditSave`:**
   - I will extend the existing `handleAccountEditSave` function (referenced at line 223 in `Settings.tsx`) to include the logic for saving the wallet's name and URL icon to Chrome local storage. 

2. **Handle Wallet Creation, Restoration, and Importation:**
   - I’ll review the various ways a user can create, import, or restore a wallet, as mentioned in the repository’s onboarding pages.
   - I’ll ensure that the wallet’s name and URL icon are saved during each process by integrating this functionality into the relevant functions.

3. **Chrome Local Storage Implementation:**
   - I’ll use the `localStorage` API to persist the wallet’s name and URL icon locally.
   - This will allow the application to retrieve the saved data when needed, ensuring a seamless user experience.

4. **Testing:**
   - I’ll write tests to ensure that the wallet’s name and URL icon are correctly saved and retrieved during wallet creation, restoration, and importation.
   - I’ll test for different edge cases, such as incomplete data, to ensure that the system handles all cases properly.

5. **User Experience:**
- Ensure the process is smooth and user-friendly, without affecting the existing wallet creation/import/restore flows.
- Display the saved wallet name and URL icon in the relevant UI sections after retrieval from local storage.

**Comment by blessingbytes** [comment]
Would love to tackle this!

**Comment by Yunusabdul38** [comment]
Would love to tackle this!

**Comment by Kaminar-i** [comment]
Please, I’d like to work on this.

**Comment by danwag06** [comment]
Please see this message...
https://github.com/bitcoin-sv/spv-wallet-browser/issues/5#issuecomment-2435570431

**Comment by jaiminRaiyani** [comment]
I'd like to take this issue.

**Comment by deeseeker** [comment]
Could I take over this issue?

**Comment by reetbatra** [comment]
Can I try solving this issue?

**Comment by jedstroke** [comment]
I am confident I can handle this task

**Comment by Aditya-040** [comment]
Mind if I take this issue?

**Comment by pheobeayo** [comment]
May I take care of this?

**Comment by Bosun-Josh121** [comment]
@danwag06  PR ready for review
