### ISSUE TITLE
Add receive notifications

### ISSUE THREAD

**Issue by danwag06** [bitcoin-sv/spv-wallet-browser#7]
With SPV, transactions sync via the background service worker asynchronously. Using the chrome storage api that is used throughout the project we could add a new item to the [Account object](https://github.com/bitcoin-sv/spv-wallet-browser/blob/c81d530f81acc2be6cc3cfd29fd3ee3782902b28/src/services/types/chromeStorage.types.ts#L35) that shows a modern notifications bell/bubble in the `TopNav` with a dropdown that gives some insights into the transactions that happened since the last time the user opened their wallet.

*The user should be able to clear these notifications from the UI and chrome local storage.

**Comment by raizo07** [comment]
Hello @danwag06 I'll like to be assigned to work on this.

**Comment by od-hunter** [comment]
Hi @danwag06 , can I be assigned this?

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am a web3 developer, I have expertise in smart contracts, decentralized technologies, and frameworks like React. I can build innovative dApps, contribute to open-source projects, educate others, and network with industry leaders to advance my career in the decentralized space.

### How I plan on tackling this issue
Use the Chrome Storage API to update the Account object with transaction insights each time a new transaction occurs. Add a notifications bell/bubble in the TopNav that displays a count of new transactions and shows a dropdown with transaction details when clicked. Ensure proper styling and functionality for the dropdown to enhance user experience.

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
**Add receive notifications**

Hello SPV Wallet Brower team,

I am Joel Vargas, and I'm a member of Dojo Coding. I also come from OnlyDust.

I would like to request the assignment of this issue. Below is my proposed approach for implementing this issue:

### How I plan on tackling this issue
### Proposal to Add Notifications for Transaction Insights in TopNav

#### Problem
Currently, transactions are synced asynchronously via the background service worker using SPV (Simplified Payment Verification). However, there is no visible way for users to track recent transactions since they last opened their wallet. This creates a gap in user experience, as they cannot easily access transaction history updates without manually navigating through the application.

#### Solution
To improve the user experience, I propose enhancing the `Account` object with a new property that displays transaction notifications in the form of a modern bell/bubble icon in the `TopNav`. This will show users insights into the transactions that have occurred since the last time they opened their wallet. The notifications can be accessed through a dropdown that provides key details about the transactions.

#### Key Features
1. **Notification Bell/Bubble in `TopNav`:** 
   - A modern notification icon (bell or bubble) will be displayed in the `TopNav` when there are new transactions.
   - This will be triggered whenever a transaction occurs via SPV while the user’s wallet is closed.

2. **Transaction Insights in Dropdown:**
   - A dropdown will appear upon clicking the notification bell/bubble.
   - The dropdown will list key information about each transaction, such as the transaction amount, date, and type (e.g., received, sent).
   - Transactions will be shown in chronological order, with the most recent at the top.

3. **Clear Notifications:**
   - Users will have the option to clear notifications from both the UI and the Chrome local storage.
   - This ensures that the notification bell/bubble resets once the user has viewed and acknowledged the transaction history.

#### Implementation Details
1. **Chrome Storage API Integration:**
   - We will use the existing `chrome.storage` API, as this is used throughout the project for storing user data.
   - A new field will be added to the `Account` object to store the list of unseen transactions.

2. **UI Updates:**
   - Add a notification bell/bubble in the `TopNav` that visually indicates when there are new transactions.
   - Create a dropdown component that shows the list of recent transactions.
   - Add a "Clear All" button to allow users to remove the notifications from both the UI and storage.

3. **Handling Sync with SPV:**
   - Ensure the background service worker continues to sync transactions asynchronously via SPV.
   - When a new transaction is detected, it will be stored locally and trigger the notification system.

#### Proposed Code Changes
1. **Account Object Update:**
   - Add a `notifications` field to the `Account` object that stores transaction details:
     ```javascript
     {
       ...otherAccountFields,
       notifications: {
         transactions: [
           {
             id: 'txid123',
             amount: '0.5 BTC',
             date: '2024-01-01',
             type: 'received'
           },
           // more transactions...
         ],
         lastSeen: '2024-01-02' // The last time the user viewed notifications
       }
     }
     ```

2. **TopNav Notification Bell Component:**
   - Add a bell/bubble icon that dynamically updates based on the number of unseen transactions.
   - Example:
     ```jsx
     <NotificationBell count={unseenTransactions.length} />
     ```

3. **Dropdown with Transaction Insights:**
   - Implement a dropdown that shows each transaction, with details like amount, date, and type.
   - Example:
     ```jsx
     <Dropdown>
       {notifications.transactions.map((tx) => (
         <TransactionItem
           key={tx.id}
           amount={tx.amount}
           date={tx.date}
           type={tx.type}
         />
       ))}
       <Button onClick={clearNotifications}>Clear All</Button>
     </Dropdown>
     ```

4. **Clear Notifications Logic:**
   - Add functionality to clear notifications both from the UI and `chrome.storage`:
     ```javascript
     const clearNotifications = () => {
       chrome.storage.local.set({ notifications: [] });
       // Update UI state
     };
     ```

#### Benefits
- **Improved UX:** Users will have a convenient way to see recent transactions without navigating away from the main screen.
- **Customizable UI:** The notification system will integrate seamlessly into the existing `TopNav` with a clean and modern design.
- **Efficient Use of Resources:** By utilizing the `chrome.storage` API already used in the project, we avoid introducing new dependencies or storage mechanisms.

#### Next Steps
- Implement the changes mentioned above.
- Test the notification system for accuracy in tracking and clearing transactions.
- Review and gather user feedback for potential refinements.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To add receive notifications for new transactions, I will use the SPV background service worker to sync transactions asynchronously and leverage the Chrome Storage API to store these notifications. A new item will be added to the Account object to track recent transactions. In the `TopNav`, a modern notification bell/bubble will be introduced, which will display a dropdown showing transaction details since the last wallet session. Users will be able to clear these notifications both from the UI and Chrome local storage, ensuring the notifications remain manageable and up-to-date. This will improve user awareness of incoming transactions in a seamless manner.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am frontend web 3 developer I have always been contribution to OD Hack project with over 55 +contribution having looking at the issue I have taken an understanding of what needs to be done here's my github profile :https://github.com/Jemiiah

### How I plan on tackling this issue
1. Update the Account object in Chrome storage: I’ll add a new `notifications`array to the `Account` type (defined in `chromeStorage.types.ts`). Each notification will contain basic transaction data such as transaction hash, amount, and timestamp.4
`export interface Account {
  // existing properties
  notifications?: Notification[]; // add this to store the notifications
}

export interface Notification {
  txHash: string;
  amount: number;
  timestamp: number;
} `

2. Modify the background service worker: Since the service worker is already syncing transactions asynchronously, I’ll hook into that logic to push new transaction notifications to Chrome storage. When a new transaction is detected, I’ll fetch the current account from storage, append the new notification, and save it back.

`chrome.storage.local.get('account', (data) => {
  const account = data.account || {};
  account.notifications = account.notifications || [];

  const newNotification: Notification = {
    txHash: transaction.hash,
    amount: transaction.amount,
    timestamp: Date.now(),
  };

  account.notifications.push(newNotification);

  chrome.storage.local.set({ account });
}); `

3. Display notifications in the TopNav: In the TopNav component, I’ll add a notification bell with a dropdown. This dropdown will show the list of notifications and allow users to clear them. I’ll use the chrome.storage API to pull the notifications from the Account object and display them.
`useEffect(() => {
  chrome.storage.local.get('account', (data) => {
    setNotifications(data.account?.notifications || []);
  });
}, []);

return (
  <div className="notification-bell">
    <Icon icon="bell" />
    {notifications.length > 0 && <span className="bubble">{notifications.length}</span>}
    <Dropdown>
      {notifications.map((notification, index) => (
        <div key={index} className="notification-item">
          <span>{notification.txHash}</span>
          <span>{notification.amount}</span>
          <span>{new Date(notification.timestamp).toLocaleString()}</span>
        </div>
      ))}
      <button onClick={clearNotifications}>Clear All</button>
    </Dropdown>
  </div>
); `

4. Clear notifications from the UI and storage: I’ll add a function to clear the notifications both from the UI and from Chrome's local storage.
`const clearNotifications = () => {
  chrome.storage.local.get('account', (data) => {
    const account = data.account;
    account.notifications = []; // clear notifications

    chrome.storage.local.set({ account }, () => {
      setNotifications([]); // update UI
    });
  });
}; `

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I'm a blockchain developer who wants to actively contribute the projects and want to fix the issues raised.

### How I plan on tackling this issue
To enhance the user experience, I will introduce a notification bell/bubble on TopNav, which is activated whenever new transactions are added to the wallet at sync time and the wallet is closed. A dropdown will be placed with transactional information aligned chronologically: amount, date, and type. Notifications may be cleared from both the UI and Chrome's local storage. I will utilize Chrome storage API for storing unseen transactions and thereby effortlessly integrate this into the already existing background sync via SPV.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
 

I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
Design Notifications Feature: I’ll add a notification system to the TopNav with a bell icon that shows the count of new transactions since the user last opened their wallet. Clicking it will display a dropdown summary of recent transactions like incoming BSV, tokens, or NFTs.

Use Chrome Storage API: I’ll use the existing Chrome Storage API to store transaction data. The service worker will sync new transactions in the background and log them to local storage. I’ll also add a field to track unseen transactions.

Service Worker for Syncing: I’ll modify the service worker to trigger notifications when new transactions are detected and store them in Chrome local storage, ready to display in the dropdown.

Notifications and Insights: The dropdown will summarize transactions such as BSV, token transfers, or NFTs, each with a link to view full details.

Clearing Notifications: Users can clear notifications from both the UI and Chrome storage. When the dropdown is opened, the notification count will reset.

Testing: I’ll ensure new transactions appear as notifications, can be cleared, and sync properly with Chrome storage.

UI/UX Refinements: I’ll refine the design for a smooth user experience and gather feedback to improve notification display and interaction.

Expected delivery: 2-4 days from assignment.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Issue #7: Add Receive Notifications

Design Notifications Feature: I’ll start by integrating a modern notification system into the TopNav, featuring a notification bell or bubble icon. This will show a count of new transactions that have occurred since the user last opened their wallet. Clicking the bell icon will reveal a dropdown displaying a summary of recent transactions, such as incoming BSV, tokens, or NFTs, with relevant details.

Leverage Chrome Storage API: I’ll utilize the existing Chrome Storage API (used throughout the project) to store the transaction data. This will allow the background service worker to sync new transactions asynchronously and log them into the local storage as they happen. I’ll add a new item to the Account object to track the number of unseen transactions since the user last interacted with the wallet.

Service Worker Integration for Syncing: Since SPV syncs transactions in the background via a service worker, I’ll modify the service worker to trigger notifications whenever a new transaction is detected. The service worker will store these transactions in the local Chrome storage, ready for display when the user interacts with the notification bell.

Notifications Dropdown and Transaction Insights: The notifications dropdown will give users insights into the types of transactions they’ve received, such as:
Incoming BSV
Token transfers (BSV20/21)
Ordinal NFT receipts
Each notification will provide a brief summary of the transaction and a link to view it in more detail, similar to the transaction history implementation.

Clearing Notifications: Users will have the option to clear notifications both from the UI and Chrome local storage. When the user clicks “clear all” in the notification dropdown, the transaction data will be marked as seen and removed from storage. I’ll also ensure that after opening the dropdown, the notification count resets, indicating that the user has viewed the new transactions.

Testing: I’ll write tests to ensure the following:
Notifications correctly display new transactions as they are synced.
Notifications can be cleared both from the UI and local storage.
The count in the notification bell resets when the user views new notifications.
The service worker properly syncs transaction data to Chrome storage.

UI/UX Refinements: I’ll work on refining the design of the notifications bell and dropdown to ensure they are user-friendly and visually consistent with the rest of the app. Feedback will be gathered on how the notifications are displayed and cleared to optimize the user experience.

Expected time of delivery = 2-4 days from being assigned.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have experience developing user interfaces and integrating background services in web applications, which will help in implementing an effective notification system.



### How I plan on tackling this issue
I would use the Chrome Storage API to track transaction updates and add a notification bell in the TopNav. The dropdown would display recent transactions, and I would implement functionality for users to clear notifications from both the UI and local storage, ensuring a streamlined user experience.

**Comment by danwag06** [comment]
@Ugo-X please confirm assignment

**Comment by Ugo-X** [comment]
Thanks chief, will get to it
